spring.application.name=shop

spring.datasource.url=jdbc:postgresql://localhost:5432/book_shop
spring.datasource.username=postgres
spring.datasource.password=123456
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order_group
spring.kafka.topic-name=order.fct.storage

logging.level.org.flywaydb=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html