# ????????? ??? ?????? ???? ?????? (??? shop-service)
spring.datasource.shop-service.url=jdbc:postgresql://localhost:5432/book_shop
spring.datasource.shop-service.username=postgres
spring.datasource.shop-service.password=123456
spring.datasource.shop-service.driver-class-name=org.postgresql.Driver
spring.datasource.shop-service.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ????????? ??? ?????? ???? ?????? (??? storage-service)
spring.datasource.storage-service.url=jdbc:postgresql://localhost:5432/Books
spring.datasource.storage-service.username=postgres
spring.datasource.storage-service.password=123456
spring.datasource.storage-service.driver-class-name=org.postgresql.Driver
spring.datasource.storage-service.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

