spring.application.name=authorization-service
spring.datasource.url=jdbc:postgresql://localhost:5432/authorization
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.hikari.maximum-pool-size=10

server.port=8080



spring.flyway.locations=classpath:db.migration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

jwt.secret=sdfsdfaf6fsd7f5sd7fd8das
jwt.expiration=3600000



logging.level.org.flywaydb=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html