spring.application.name=authorization-service
spring.datasource.url=jdbc:postgresql://localhost:5432/application_builder
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.hikari.maximum-pool-size=10

server.port=8080



spring.flyway.locations=classpath:db.migration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

jwt.secret-key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt.expiration=3600000



logging.level.org.flywaydb=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html